sudo: false

os:
  - linux

language:
  - python

python:
  - "3.7"

services:
  - docker

before_script:
  - docker build -t elbenfreund:hamster-gtk-devel -f ./ci/dockerfile .

script:
    # See: https://docs.codecov.io/docs/testing-with-docker for details
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run -v /home/travis/build/projecthamster/hamster-gtk:/hamster-gtk $ci_env elbenfreund:hamster-gtk-devel ./ci/run_docker.sh
